name: sqflite_migration_plan
description: Flexible migrations for sqflite with a clear concise syntax.
version: 0.1.0
homepage: https://github.com/ilikerobots/sqflite_migration_plan

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.0-nullsafety.1
  test: ^1.15.7
  path:
  sqflite_common:
  sqflite_common_ffi:

# The following section is specific to Flutter.
flutter:
